# Generated by Django 6.1.2 on 2026-10-07 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('customer', '0002_alter_customer_neighborhood_alter_customer_number_and_more'),
        ('quote', '0002_quote_created_at_quote_heating_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='heating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='catalog.heatingoption'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='catalog.poolmodel'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='water_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='catalog.watertreatment'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='waterfall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='catalog.waterfall'),
        ),
    ]
