# Generated by Django 6.1.2 on 2026-10-07 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_lighting_unit_price_lighting_price_and_more'),
        ('quote', '0003_alter_quote_customer_alter_quote_heating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='lighting_unit_price',
            new_name='lighting_price',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='lighting_quantity',
        ),
        migrations.AddField(
            model_name='quote',
            name='lighting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.lighting'),
        ),
    ]
