# Generated by Django 6.1.2 on 2026-10-08 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_lighting_unit_price_lighting_price_and_more'),
        ('quote', '0004_rename_lighting_unit_price_quote_lighting_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='lighting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='catalog.lighting'),
        ),
    ]
