# Generated by Django 6.1.2 on 2026-10-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_alter_quote_lighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='validity_days',
            field=models.PositiveIntegerField(default=10, verbose_name='Validade em dias'),
        ),
    ]
