# Generated by Django 6.1.2 on 2026-10-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_quote_valid_until_quote_validity_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='commercial_notes',
            field=models.TextField(blank=True, verbose_name='Observações comerciais'),
        ),
    ]
