# Generated by Django 6.1.2 on 2026-10-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('document', models.CharField(max_length=18, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=15)),
                ('postal_code', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
