# Generated by Django 6.1.2 on 2026-10-08 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('quote_created', 'Orçamento criado'), ('quote_updated', 'Orçamento atualizado'), ('quote_deleted', 'Orçamento excluído'), ('quote_approved', 'Orçamento aprovado'), ('quote_sent', 'Orçamento enviado'), ('customer_created', 'Cliente cadastrado'), ('customer_updated', 'Cliente atualizado'), ('customer_deleted', 'Cliente excluído'), ('catalog_updated', 'Catálogo atualizado')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
