# Generated by Django 6.1.2 on 2026-10-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('quote_created', 'Orçamento criado'), ('quote_updated', 'Orçamento atualizado'), ('quote_deleted', 'Orçamento excluído'), ('quote_approved', 'Orçamento aprovado'), ('quote_sent', 'Orçamento enviado'), ('quote_rejected', 'Orçamento rejeitado'), ('quote_cancelled', 'Orçamento cancelado'), ('customer_created', 'Cliente cadastrado'), ('customer_updated', 'Cliente atualizado'), ('customer_deleted', 'Cliente excluído'), ('catalog_updated', 'Catálogo atualizado')], max_length=30),
        ),
    ]
