# Generated by Django 6.1.2 on 2026-10-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pools/'),
        ),
    ]
