# Generated by Django 6.1.2 on 2026-10-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_poolmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lighting',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='lighting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lighting',
            name='type',
            field=models.CharField(choices=[('kit_2', 'Kit 2 LEDs'), ('kit_4', 'Kit 4 LEDs')], default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
