# Generated by Django 6.1.2 on 2026-10-08 23:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_lighting_unit_price_lighting_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatingoption',
            name='measure',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='A medida deve ser maior que zero.')]),
        ),
        migrations.AlterField(
            model_name='heatingoption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='O valor não pode ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='lighting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='O valor não pode ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='poolmodel',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='O valor não pode ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='poolmodel',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='A medida deve ser maior que zero.')]),
        ),
        migrations.AlterField(
            model_name='poolmodel',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='A medida deve ser maior que zero.')]),
        ),
        migrations.AlterField(
            model_name='waterfall',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='O valor não pode ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='watertreatment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='O valor não pode ser negativo.')]),
        ),
        migrations.AddConstraint(
            model_name='heatingoption',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='heating_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='heatingoption',
            constraint=models.CheckConstraint(condition=models.Q(('measure__gt', 0)), name='heating_measure_positive'),
        ),
        migrations.AddConstraint(
            model_name='lighting',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='lighting_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='poolmodel',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='pool_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='poolmodel',
            constraint=models.CheckConstraint(condition=models.Q(('length__gt', 0), ('width__gt', 0)), name='pool_dimensions_positive'),
        ),
        migrations.AddConstraint(
            model_name='waterfall',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='waterfall_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='watertreatment',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='treatment_price_non_negative'),
        ),
        migrations.AlterConstraint(
            model_name='heatingoption',
            name='unique_heating_type_measure',
            constraint=models.UniqueConstraint(fields=('type', 'measure'), name='unique_heating_type_measure', violation_error_message='Já existe um aquecimento com este tipo e esta medida.'),
        ),
        migrations.AlterConstraint(
            model_name='poolmodel',
            name='unique_pool_model_size',
            constraint=models.UniqueConstraint(fields=('model', 'length', 'width'), name='unique_pool_model_size', violation_error_message='Já existe uma piscina com este modelo e estas medidas.'),
        ),
    ]
